name = "CoolProp"
uuid = "e084ae63-2819-5025-826e-f8e611a84251"
version = "0.1.1"

[deps]
CoolProp_jll = "3351c21f-4feb-5f29-afb9-f4fcb0e27549"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CoolProp_jll = "6.4"
julia = "1.3"
Unitful="1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
